apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  namespace: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: bishalmandal/nodeapp:v1
          ports:
            - containerPort: 3000
